name: Ruby

on:

  fork:

  schedule:
    - cron: '*/7 * * * *'

jobs:

  run:
    if: github.repository != 'OffendedUkrainian/stop-russian-agression'
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.0'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Say Hello
      run: bundle exec rake app:say_hello
